ratebeer/config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_freezed', on: :member
  end

  resources :memberships do
    post 'confirm_membership', on: :member
  end

  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  
  
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]
  

end

ratebeer/app/models/user.rb
class User < ActiveRecord::Base
	include RatingAverage
	
	has_secure_password
	validates :password, :format => {:with => /(?=.*[A-Z])(?=.*[0-9]).{4,}/, message: "must be at least 4 characters and include one number and one capital letter."}
	
	validates :username, uniqueness: true
	validates :username, length: { minimum: 3, maximum: 15 }
	has_many :ratings, dependent: :destroy   # käyttäjällä on monta ratingia
	has_many :beers, through: :ratings
	has_many :memberships, dependent: :destroy
	has_many :beer_clubs, through: :memberships

	def favorite_beer
		return nil if ratings.empty?
		ratings.order(score: :desc).limit(1).first.beer
	end

	def favorite_style
		return nil if ratings.empty?
		highest_average(ratings.map { |r| [r.beer.style, r.score] })
	end

	def highest_average (datamap)
		ha = Hash.new { |h, k| h[k] = [] }
		hb = Hash.new { |h, k| h[k] = [] }
		datamap.each { |r| ha[r[0]] << r[1] }
		ha.each { |k, value| hb[k] << value.sum/value.count.to_f }
		hb.key(hb.values.max)
	end

	def favorite_brewery
		return nil if ratings.empty?
		highest_average(ratings.map{|r| [r.beer.brewery, r.score]})
	end

	def to_s
		"#{username}"
	end

	def self.top(n)
		sorted_by_rating_in_desc_order = User.all.sort_by{ |b| -(b.ratings.count||0) }
		sorted_by_rating_in_desc_order[0..n-1]
		# palauta listalta parhaat n kappaletta
		# miten? ks. http://www.ruby-doc.org/core-2.1.0/Array.html
	end

end

ratebeer/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_admin, only: [:destroy, :toggle_freezed]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy if current_user == @user
	session[:user_id]=nil
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_freezed
    user = User.find(params[:id])
    user.update_attribute :freezed, (not user.freezed)

    new_status = user.freezed? ? "freezed" : "active"

    redirect_to :back, notice:"user activity status changed to #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

ratebeer/app/helpers/users_helper.rb
module UsersHelper
end

ratebeer/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if @user.new_record? %>
		<div class="field">
			<%= f.label :username %><br />
			<%= f.text_field :username %>
		</div>
	<% end %>

	<div class="field">
	<% if @user.new_record? %>
		<%= f.label :password %><br />
	<% else %>
		<%= f.label 'New password' %><br />
	<% end %>
		<%= f.password_field :password %>
	</div>

  
  
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ratebeer/app/views/users/edit.html.erb
<h1><%="Change password of #{@user.username}"%></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

ratebeer/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Username</th>
    <th> rated beers </th>
    <th> total ratings </th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>

        <td>
          <% if current_user and current_user.admin %>
              <% if user.freezed %>


                <td><span class="label label-info">freezed</span></td>
            <% end %>
        <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path , class:"btn btn-success"%>

ratebeer/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

ratebeer/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>



<% if current_user and current_user.admin  %>

    <% if @user.freezed  %>
        <span class="label label-info">freezed</span>
    <% end %>

    <%= link_to "#{@user.freezed? ? "reactivate" : "freeze"} account", toggle_freezed_user_path(@user.id), method: :post, class: "btn btn-warning" %>
<% end %>


<p>
  <%= "This user has made #{pluralize(@user.ratings.count, 'rating')} with average of #{round(@user.average_rating)}"%>
</p>

<%if @user.favorite_style%>
    <p>
      <%= "Favorite style: #{@user.favorite_style.style}"%>
    </p>
<% end %>

<%if @user.favorite_brewery%>
    <p>
      <%= "Favorite brewery: #{@user.favorite_brewery.name}" %>
    </p>
<% end %>

<p>
  member of<br>
  <% @user.beer_clubs.each do |club| %>
      <% if club.memberships.find_by(user_id:@user.id).confirmed? %>
          <%= link_to club.name, beer_club_path(club.id) %>
      <% end %>
  <% end %>
</p>

<p>
  applied membership of<br>
  <% @user.beer_clubs.each do |club| %>
      <% unless club.memberships.find_by(user_id:@user.id).confirmed? %>
          <%= link_to club.name, beer_club_path(club.id) %>
      <% end %>
  <% end %>
</p>

<ul>
  <% @user.ratings.each do |rating| %>
      <li>
        <%= rating %>
        <% if @user == current_user %>
            <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' %>
        <% end %>
      </li>
  <% end %>
</ul>
<% if @user == current_user %>
    <%= link_to 'Destroy', user_path, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' %> |
    <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-warning" %> |
<% end %>
<%= link_to 'Back', users_path, class:"btn btn-info" %>