ratebeer/config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_freezed', on: :member
  end

  resources :memberships do
    post 'confirm_membership', on: :member
  end

  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  
  
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]
  

end

ratebeer/app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
	has_many :memberships, dependent: :destroy
	has_many :users, through: :memberships
	
	validates :name, presence: true
	validates :city, presence: true
	validates :founded, numericality: {only_integer: true }
end

ratebeer/app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_admin, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club=@beer_club
    @membership.user_id = current_user
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        Membership.create(beer_club_id:@beer_club.id, user_id:current_user.id, confirmed:true)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

ratebeer/app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

ratebeer/app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ratebeer/app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

ratebeer/app/views/beer_clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club, class:"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club), class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer club', new_beer_club_path, class:"btn btn-success"%>

ratebeer/app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

ratebeer/app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer_club.name %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beer_club.city %>
</p>


<% if current_user %>
    <% @membership.user=current_user %>
    <% if current_user.beer_clubs.find_by id: @beer_club.id %>

        <% @membership=Membership.all.where(user_id:current_user.id, beer_club_id:@beer_club.id).first %>
        <%= form_for(@membership, method: "delete") do |f| %>
            <%= f.submit value: "end the membership", class:"btn btn-danger" %>
        <% end %>
    <% else %>

        <%= form_for(@membership) do |f| %>
            <%= f.hidden_field :beer_club_id %>
            <%= f.hidden_field :user_id %>
            <%= f.submit value: "join the club", class:"btn btn-success" %>

        <% end %>
    <% end %>
<% end %>

<h2><strong>Members</strong></h2>

<ul>
  <% @beer_club.users.each do |user| %>
      <% if user.memberships.find_by(beer_club_id:@beer_club.id).confirmed? %>
          <li> <%= link_to user.username, user_path(user.id) %> </li>

      <% end %>
  <% end %>
</ul>

<% if current_user and current_user.memberships.find_by(beer_club_id:@beer_club.id)%>
    <h2><strong>Waiting confirmation</strong></h2>

    <ul>
      <% @beer_club.users.each do |user| %>
          <% unless user.memberships.find_by(beer_club_id:@beer_club.id).confirmed? %>
              <li>

                <%= link_to user.username, user_path(user.id) %>
                <% if current_user.memberships.find_by(beer_club_id:@beer_club.id).confirmed %>
                    <%= link_to "confirm membership", confirm_membership_membership_path(user.memberships.find_by(beer_club_id:@beer_club.id).id), method: :post, class: "btn btn-primary" %>
                <% end %>
              </li>


          <% end %>
      <% end %>
    </ul>

<% end %>

<%= link_to 'Edit', edit_beer_club_path(@beer_club), class:"btn btn-warning" %> |
<%= link_to 'Back', beer_clubs_path, class:"btn btn-info" %>